name: cowSPLOSION
version: 1.0.0.0
api-version: 1.15
load: POSTWORLD
description: Causes cows to explode when attacked with additional options.
author: pyropyro78
main: com.pyromanticgaming.cowsplosion.cowSPLOSION

